// Start pipline's job

GET http://localhost:9609/start/1/2/3
Content-Type: application/json

> {%
 client.log(response.body);
 client.assert(response.body, 3);
%}

###

// Stop pipline's job

GET http://localhost:9609/stop/3
Content-Type: application/json

> {%
 client.log(response.body);
 client.assert(response.body, 3);
%}

###

// Update pipline's job status

POST http://localhost:9609/status
Content-Type: application/json

{
  "pipelineId": 1,
  "group": "group-test",
  "title": "title-test",
  "message": "message-test"
}

> {%
 client.log(response.body);
 client.assert(response.body, 3);
%}

###

// Get pipline's job status

GET http://localhost:9609/3

> {%
 client.log(response.body);
 client.assert(response.body, 'pong!');
%}

###

// Ping request

GET http://localhost:9609/ping

> {%
 client.log(response.body);
 client.assert(response.body, 'pong!');
%}

###

